### ISSUE TITLE
Does the statement of cm-statement not support the variable?

### ISSUE THREAD

**Issue by wallishuang** [peterprib/node-red-contrib-connectionmanager#17]
Hi ,
   I have set the insert sql in msg.payload at previous node, so in the cm-statement , I need to set the msg.payload at statement field, but it seems doesn't work?

**Comment by peterprib** [comment]
Haven't designed the interface to run sql built in another process.  It was to deal with parameters and if the underlying technology allowed usage of parameter markers which has a performance boost, cleaner technology for running sql with variable information plus avoid security issues inherit in the use of dynamic sql.  If you have a use case for dynamic SQL I could enhance but be aware for dynamic SQL, it would lose key features mentioned above.   Rather than statement it would just have location for statement.  By definition would have no parameters.  If you expect both parameters and dynamic SQL may required  more thought as what happens if dynamic sql doesn't match markers in sql plus there would be overhead as the javascript would have to do replacement each execution rather than at node build phase.   I will close issue and if you desire improvements then provide more details on use case and maybe why you want dynamically built SQL and the if parameter markers are required and expectation on how handled.
